#!/usr/bin/python3
#IMPORT OF LIBRERY
from MParLoc import Launcher 
from MParLoc import grid_creator
##############################
grid_creator('EXAMPLE','sac') 
# RUN THE GRID CREATOR CODE THAT READ THE NONLINLOC GRIDS 
#AND CREATE A DIFFERENTIAL AMPLITUDE AND BACK-AZIMUT GRIDS
Launcher('EXAMPLE','sac')
# RUN THE GRID CREATOR CODE THAT READ THE NONLINLOC GRIDS 
#AND CREATE A DIFFERENTIAL AMPLITUDE AND BACK-AZIMUT GRIDS